###
GET http://localhost:3000/api/license
###
GET http://localhost:3000/api/license/10
###
POST http://localhost:3000/api/license
Content-Type: application/json

{
    "type":"รถจักยานยนต์",
    "expiryDate":"11/12/60",
    "lssueData":"11/12/65",
    "licensenumber":"1472571"
}

###
POST http://localhost:3000/api/license
Content-Type: application/json

{
    "type":"รถสี่ล้อ",
    "expiryDate":"10/12/60",
    "lssueData":"10/12/70",
    "licensenumber":"147257"
}
###
PUT http://localhost:3000/api/license/2
Content-Type: application/json

{
    "type":"รถสี่ล้อ2",
    "expiryDate":"10/12/60",
    "lssueData":"10/12/75",
    "licensenumber":"1472574"
}
###
DELETE http://localhost:3000/api/license/14

###
DELETE http://localhost:3000/api/license/999

